In [ ]:
##Question 1)
##         C) True
##Question 2)
##         D) All of the above 
##Question 3)
##         A) + positive
##         B) + positive 

In [9]:
##Question 4)
import numpy as np
##Creating the two arrays
a = np.array([1,3])
b = np.array([2,3])

In [10]:
a

array([1, 3])

In [11]:
b

array([2, 3])

In [12]:
a - b 

array([-1,  0])

In [13]:
np.power(a-b,2)

array([1, 0], dtype=int32)

In [14]:
np.sum(np.power(a-b,2))

1

In [15]:
##calculating the eucladian distance 
np.sqrt(np.sum(np.power(a-b,2)))

1.0