In [ ]:
##question 1)
##         C) both classification and regression
##question 2)
##         D) all of the above
##question 3) 
##         A) 1.8
##         B) 3.1

In [1]:
import numpy as np

##creating array
a = np.array([1,3,5,7,13])
a

array([ 1,  3,  5,  7, 13])

In [4]:
##0 - 1 transformation
a_min = np.min(a)
a_max = np.max(a)
(a - a_min) / (a_max - a_min)

array([0.        , 0.16666667, 0.33333333, 0.5       , 1.        ])

In [5]:
## z-score standardization
a_mean = np.mean(a)
a_sd = np.std(a, ddof = 1)
(a - a_mean) / a_sd

array([-1.04249338, -0.60812114, -0.1737489 ,  0.26062335,  1.56374007])